# Numpy Exercise  <img src = "numpy1.png">
###### Authored by T.K.Senthil Kumar

#### 1. Create a numpy array with the number of elements equals your age. The value of array elements is a random number between 10 to your age 

In [1]:
import numpy as np

In [2]:
age = int(input('Enter your age:'))
age_array = np.random.randint(10,age+1,age)
print(age_array,'\n')
print(age_array.size)

Enter your age:25
[11 24 11 22 25 15 17 18 25 24 17 18 17 15 21 14 16 23 22 15 15 21 19 11
 21] 

25


#### 2. Create a numpy array between 1 to 50 with the span(space) of 2 and print the length of the array

In [3]:
num_array = np.arange(1,51,2)
print('Array:',num_array)
print('Length:',len(num_array))

Array: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]
Length: 25


#### 3. Create an equally spaced numpy array with 27 elements between 4 and 7 

In [4]:
spaced_array = np.linspace(4,7,num=27,endpoint=True)
print(spaced_array)

[4.         4.11538462 4.23076923 4.34615385 4.46153846 4.57692308
 4.69230769 4.80769231 4.92307692 5.03846154 5.15384615 5.26923077
 5.38461538 5.5        5.61538462 5.73076923 5.84615385 5.96153846
 6.07692308 6.19230769 6.30769231 6.42307692 6.53846154 6.65384615
 6.76923077 6.88461538 7.        ]


#### 4. Create a matrix of size (5 x 4) with random numbers and round off the each elements by only 2 fractional points.

In [5]:
matrix_1 = np.random.randn(5,4)
print('Matrix before rounding off:\n',matrix_1)
rounded_matrix_1 = np.round(matrix_1,decimals=2)
print('\nMatrix after rounding off:\n',rounded_matrix_1)

Matrix before rounding off:
 [[ 0.32699096  0.54112978 -1.38378469 -0.82015776]
 [-0.03323305 -0.0425674   0.31122501  0.12395205]
 [ 0.02850866  0.98633448 -0.35628841  0.54710279]
 [ 0.40057069  1.35607143  0.78102245 -0.22576118]
 [ 0.28719463  0.03065548 -0.08369189 -2.95381017]]

Matrix after rounding off:
 [[ 0.33  0.54 -1.38 -0.82]
 [-0.03 -0.04  0.31  0.12]
 [ 0.03  0.99 -0.36  0.55]
 [ 0.4   1.36  0.78 -0.23]
 [ 0.29  0.03 -0.08 -2.95]]


#### 5. Create a matrix of size (5x5) with random integers between 5 to 15

In [6]:
matrix_2 = np.random.randint(5,15,size=(5,5))
print(matrix_2)

[[10 14  5 12  7]
 [ 8 10  7 13  9]
 [ 9 10  5  9 12]
 [12  6  9 13  7]
 [13 10  9 11  7]]


#### 6. Create the one dimensional array of zeros of random length below 20 with the data type int32

In [7]:
one_dim_zeros = np.zeros(np.random.randint(1,20),dtype='int32')
print(one_dim_zeros)
print('\nDtype:',one_dim_zeros.dtype)
print('\nShape:',one_dim_zeros.shape)

[0 0 0 0 0 0 0 0 0 0 0 0]

Dtype: int32

Shape: (12,)


#### 7. Create a two dimensional array of ones of random row and column lengths with the data type of float32 

In [8]:
rows = np.random.randint(1,20)
cols = np.random.randint(1,20)
two_dim_ones = np.ones((rows,cols),dtype='float32')
print(two_dim_ones)
print('\nShape:',two_dim_ones.shape)
print('\nDtype:',two_dim_ones.dtype)

[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]

Shape: (2, 9)

Dtype: float32


#### 8. Create a matrix exactly as same as shown below and print its shape, type and dtype
<img src = "np_mat1.png">

In [9]:
sample_matrix = np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6],[23,12,8,5,8]])
print(sample_matrix)
print('Shape: ',sample_matrix.shape)
print('Type: ',type(sample_matrix))
print('Dtype: ',sample_matrix.dtype)

[[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6 54  6]
 [23 12  8  5  8]]
Shape:  (5, 5)
Type:  <class 'numpy.ndarray'>
Dtype:  int64


#### 9. Access the center pixel of the matrix defined in the question no 8 ( Don't enter the row and column index explicitely)

In [10]:
num_of_rows = sample_matrix.shape[0]
num_of_cols = sample_matrix.shape[1]
center_of_matrix = sample_matrix[num_of_rows//2,num_of_cols//2]
print(center_of_matrix)

3


#### 10. Print the all the elements of 3rd row of the matrix

In [11]:
print(sample_matrix[2])

[ 5  7  3 76  3]


#### 11. Print the all the elements of 4th columns of the matrix

In [12]:
print(sample_matrix[:,3])

[34 65 76 54  5]


#### 12. Print the 4 corner pixels of the matrix

In [13]:
print('Corners from 1st row:\n',sample_matrix[0,0],'\n',sample_matrix[0,4])
print('Corners from last row:\n',sample_matrix[4,0],'\n',sample_matrix[4,4])

Corners from 1st row:
 9 
 45
Corners from last row:
 23 
 8


#### 13. Create three matrix m1,m2,m3 with the elements grouped in the figure below
<img src = "np_mat2.png">

In [14]:
m1 = sample_matrix[:2,2:4]
m2 = sample_matrix[3:,:2]
m3 = sample_matrix[2:,2:]

print('m1\n',m1,'\n')
print('m2\n',m2,'\n')
print('m3\n',m3,'\n')

m1
 [[50 34]
 [34 65]] 

m2
 [[ 7  8]
 [23 12]] 

m3
 [[ 3 76  3]
 [ 6 54  6]
 [ 8  5  8]] 



#### 14. Reshape all the three matrix segmented in the above task in to three  1-dimensional vector.

In [15]:
print(m1.reshape(4,),'\n')
print(m2.reshape(4,),'\n')
print(m3.reshape(9,),'\n')

[50 34 34 65] 

[ 7  8 23 12] 

[ 3 76  3  6 54  6  8  5  8] 



#### 15. Concatenate the matrix m1 and m2 in both vertical and horizontal direction

In [16]:
print('Concatenation in vertical direction')
print(np.concatenate((m1,m2),axis=0))
print('\nConcatenation in horizontal direction')
print(np.concatenate((m1,m2),axis=1))

Concatenation in vertical direction
[[50 34]
 [34 65]
 [ 7  8]
 [23 12]]

Concatenation in horizontal direction
[[50 34  7  8]
 [34 65 23 12]]


#### 16. Add, Subtract, multiply, divide the matrixes m1 and m2

In [17]:
print('Add m1 and m2')
print(m1 + m2)
print('\nSubtract m2 from m1')
print(m1 - m2)
print('\nMultiply m1 by m2')
print(m1 * m2)
print('\nDivide m1 by m2')
print(m1 / m2)

Add m1 and m2
[[57 42]
 [57 77]]

Subtract m2 from m1
[[43 26]
 [11 53]]

Multiply m1 by m2
[[350 272]
 [782 780]]

Divide m1 by m2
[[7.14285714 4.25      ]
 [1.47826087 5.41666667]]


#### 17. Add the m1 with m3 by removing the first row and last column of m3

In [18]:
m1 + m3[1:,:2]

array([[56, 88],
       [42, 70]])

#### 18. Form the matrix m4 by concatenating (as a new row) the vector [me1, me2] with the matrix m1, where me1 and me2 are the mean values of each column on m1.

In [19]:
m1

array([[50, 34],
       [34, 65]])

In [20]:
# Finding mean values of each column of m1
me1 = m1[:,0].mean()
me2 = m1[:,1].mean()
print('Mean value of 1st column of m1:\n',me1,'\n')
print('Mean value of 2nd column of m1:\n',me2,'\n')

# Creating a vector and reshaping
temp_mat = np.array([me1,me2])
temp_mat = temp_mat.reshape(1,2)

# Concatenating
m4 = np.concatenate((m1,temp_mat),axis=0)
print('Matrix after concatenating with mean values:\n',m4)

Mean value of 1st column of m1:
 42.0 

Mean value of 2nd column of m1:
 49.5 

Matrix after concatenating with mean values:
 [[50.  34. ]
 [34.  65. ]
 [42.  49.5]]


#### 19. Perform the matrix multiplication between m3 and m4

In [21]:
print('m3:\n',m3,'\n')
print('m4:\n',m4)
print('\nMatrix Multiplication between m3 and m4:\n')
print(np.matmul(m3,m4))

m3:
 [[ 3 76  3]
 [ 6 54  6]
 [ 8  5  8]] 

m4:
 [[50.  34. ]
 [34.  65. ]
 [42.  49.5]]

Matrix Multiplication between m3 and m4:

[[2860.  5190.5]
 [2388.  4011. ]
 [ 906.   993. ]]


#### 20. Compute the maximum and minimum value of mean, variance, standard deviation for each row of matrix created in question number 8.

In [22]:
print('Matrix for reference:\n',sample_matrix,'\n')

print('Mean of each row of the matrix:\n',sample_matrix.mean(axis=1),'\n')
print('Minimum of mean:\n',sample_matrix.mean(axis=1).min(),'\n')
print('Maximum of mean:\n',sample_matrix.mean(axis=1).max(),'\n')

print('Variance of each row of the matrix:\n',sample_matrix.var(axis=1),'\n')
print('Minimum of variance:\n',sample_matrix.var(axis=1).min(),'\n')
print('Maximum of variance:\n',sample_matrix.var(axis=1).max(),'\n')

print('Standard deviation of each row of the matrix:\n',sample_matrix.std(axis=1),'\n')
print('Minimum of standard deviation:\n',sample_matrix.std(axis=1).min(),'\n')
print('Maximum of standard deviation:\n',sample_matrix.std(axis=1).max())

Matrix for reference:
 [[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6 54  6]
 [23 12  8  5  8]] 

Mean of each row of the matrix:
 [32.6 27.6 18.8 16.2 11.2] 

Minimum of mean:
 11.2 

Maximum of mean:
 32.6 

Variance of each row of the matrix:
 [214.64 548.24 820.16 357.76  39.76] 

Minimum of variance:
 39.760000000000005 

Maximum of variance:
 820.1600000000001 

Standard deviation of each row of the matrix:
 [14.65059726 23.41452541 28.63843571 18.91454467  6.30555311] 

Minimum of standard deviation:
 6.305553108173779 

Maximum of standard deviation:
 28.63843571147


#### 21. Compute the average and strike rate for each player and sort it decending way (seperately for avg and strike rate)
<img src = 'crick1.png'>

In [23]:
runs_scored = np.array([[54,60,10,65],[102,2,78,32],[3,110,1,92],[56,6,12,42],[12,8,22,11]])
balls_faced = np.array([[50,42,22,78],[95,8,65,43],[9,100,7,101],[27,3,11,31],[24,20,36,27]])

avg_runs = runs_scored.mean(axis=1).reshape(5,1)

tot_runs = runs_scored.sum(axis=1).reshape(5,1)
tot_balls = balls_faced.sum(axis=1).reshape(5,1)
strike_rate = np.round(tot_runs/tot_balls * 100,decimals=2)

avg_runs_and_strike_rate = np.concatenate((runs_scored,avg_runs,strike_rate),axis=1)

print('Runs Scored in 4 Matches:\n',runs_scored,'\n')
print('Balls Faced in 4 Matches:\n',balls_faced,'\n')
print('Average Runs and Strike Rate Concatenated with Runs Scored:\n',avg_runs_and_strike_rate,'\n')

sorted_desc_avg_runs = np.concatenate((runs_scored,avg_runs,strike_rate),axis=1)
sorted_desc_avg_runs = sorted_desc_avg_runs[sorted_desc_avg_runs[:,4].argsort()[::-1]]

print('Average Runs sorted in Descending order:\n',sorted_desc_avg_runs,'\n')

sorted_desc_strikerate = np.concatenate((runs_scored,avg_runs,strike_rate),axis=1)
sorted_desc_strikerate = sorted_desc_strikerate[sorted_desc_strikerate[:,5].argsort()[::-1]]
print('Average Strike Rate sorted in Descending order:\n',sorted_desc_strikerate)

Runs Scored in 4 Matches:
 [[ 54  60  10  65]
 [102   2  78  32]
 [  3 110   1  92]
 [ 56   6  12  42]
 [ 12   8  22  11]] 

Balls Faced in 4 Matches:
 [[ 50  42  22  78]
 [ 95   8  65  43]
 [  9 100   7 101]
 [ 27   3  11  31]
 [ 24  20  36  27]] 

Average Runs and Strike Rate Concatenated with Runs Scored:
 [[ 54.    60.    10.    65.    47.25  98.44]
 [102.     2.    78.    32.    53.5  101.42]
 [  3.   110.     1.    92.    51.5   94.93]
 [ 56.     6.    12.    42.    29.   161.11]
 [ 12.     8.    22.    11.    13.25  49.53]] 

Average Runs sorted in Descending order:
 [[102.     2.    78.    32.    53.5  101.42]
 [  3.   110.     1.    92.    51.5   94.93]
 [ 54.    60.    10.    65.    47.25  98.44]
 [ 56.     6.    12.    42.    29.   161.11]
 [ 12.     8.    22.    11.    13.25  49.53]] 

Average Strike Rate sorted in Descending order:
 [[ 56.     6.    12.    42.    29.   161.11]
 [102.     2.    78.    32.    53.5  101.42]
 [ 54.    60.    10.    65.    47.25  98.44]
 [  3. 

#### 22. The students mark was recorded in a numpy array: marks = np.array([65,84,47,56,89,98,48,77,80,39]).  Cutoff for pass is 50 marks. Write the logic to print the number of students passed and failed. 

In [24]:
marks = np.array([65,84,47,56,89,98,48,77,80,39])

count_failed = (marks < 50).sum()
count_passed = (marks >= 50).sum()

print('Marks:\n',marks,'\n')
print('Number of students passed:\n',count_passed)
print('Number of students failed:\n',count_failed)

Marks:
 [65 84 47 56 89 98 48 77 80 39] 

Number of students passed:
 7
Number of students failed:
 3


#### 23. The class incharge decided to give a mercy mark of 5 for those who scored between 45 and 49. Also the bonus of 5 marks awarded to the students who scored more than 80. Print all the student marks and compute the increase in the pass percentage of class. Any score more than 100 must be recorded as only 100.

In [25]:
marks_new = marks.copy()

for i in range(len(marks_new)):
    if (marks_new[i] >= 45 and marks_new[i] <= 49) or (marks_new[i] > 80):
        marks_new[i] += 5
        if marks_new[i] > 100:
            marks_new[i] = 100
            
print('Marks after adjusting mercy marks and bonus marks:\n',marks_new,'\n')

count_failed_new = (marks_new < 50).sum()
count_passed_new = (marks_new >= 50).sum()

orig_pass_percent = (count_passed / len(marks)) * 100
new_pass_percent = (count_passed_new / len(marks_new)) * 100
percent_change = np.round(((new_pass_percent - orig_pass_percent) / orig_pass_percent) * 100, decimals=2)

print('Change in pass percentage:\n', percent_change)


Marks after adjusting mercy marks and bonus marks:
 [ 65  89  52  56  94 100  53  77  80  39] 

Change in pass percentage:
 28.57


#### 24. Print the time taken for performing the following operation using list and numpy array
####       (x(i)^2 +8) / y(i),   where x and y are real integers from 1 to 60000

In [26]:
import time

list1 = list(range(1,60000))
list2 = list(range(1,60000))
array1 = np.arange(1,60000)
array2 = np.arange(1,60000)

time_bf_list_operation = time.time()

list_op = [(x**2+8)/y for x,y in zip(list1,list2)]

time_af_list_operation = time.time()

print('Time taken for list operation in seconds:', time_af_list_operation - time_bf_list_operation)

time_bf_array_operation = time.time()

array_op = (array1**2+8)/array2

time_af_array_operation = time.time()

print('Time taken for array operation in seconds:', time_af_array_operation - time_bf_array_operation)


Time taken for list operation in seconds: 0.02135300636291504
Time taken for array operation in seconds: 0.004355192184448242


#### 25. Create a Github account and upload your solution with the short write-up on Numpy

#### Solution

https://github.com/mkanchanag/NumPy-Assignment